Milestone 3 : Add a contact form and finish the mobile version
dqarias/Portafolio pull request #3
Opened 2022-04-27 05:26 UTC by dqarias

In this milestone we:

- Create forms with HTML5 validations.
- Add the contact form in the footer.

2022-04-27 06:20 UTC, gtekle requested changes
Hi **@TEAM** :wave:, 

Good job so far! :clap: :clap: :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!
![dog-pug](https://user-images.githubusercontent.com/44057863/165453887-c590fe3d-fb6b-4d60-819c-4d975d94fe91.gif)



## Highlights
:heavy_check_mark: Nice UI
:heavy_check_mark: Meaningful commit messages
:heavy_check_mark: Good use of GitHub flow

## Required Changes ♻️
_Check the comments under the review._

- [ ] You should use the padding of 24px for the form elements in the contact-me section as in the Figma design. Please take a look at the snapshot for a device size 375px width:

#### Figma Design    
![contact-form-padding-figma](https://user-images.githubusercontent.com/44057863/165453280-cb9a611e-c2fe-4589-abef-ba511b831c66.png) 
### Implementation
![contact-form-padding-impl-375px](https://user-images.githubusercontent.com/44057863/165453300-5a61e785-65ef-4d94-bdcf-0e49dcef7ff2.png) |

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 06:20 UTC, gtekle commented on README.md
>  # Hello Microverse
- [ Optional ] You should update the project title from `Hello Microverse` to `Portfolio` to reflect the project you are working on.

2022-04-27 06:20 UTC, gtekle commented on README.md
> +> This is the third milestone of my portafolio project. For this part I and My coding partnert  have worked using pair programing methodology. We set up the project using best practices (linters, Git
- [ Optional ] The description section you README is for the overall project - Portfolio in this case. Therefore, you should add a description for the whole project. But, you can add to it as you progress through the module.

2022-04-27 06:20 UTC, gtekle commented on index.html
> +      <fieldset>
- [ ] The semantic use of `<fieldset>` is to group related form elements together. Therefore, you should remove it. Please see this [reference](https://www.w3schools.com/tags/tag_fieldset.asp)

2022-04-27 06:20 UTC, gtekle commented on index.html
> +        <form
- [ ] The semantically meaningful ordering of elements in the footer section, can be something like:
```
<footer>
    <section class="contact-me">
        <div>
            <h2> Contact Me </>
            <p> If you have an application you... </p>
        <div>
        <form action= >
        </form>
    </section>
    
    // here you can add other section such as foot navigation links, etc later on.
</footer>
```

2022-04-27 06:20 UTC, gtekle commented on index.html
> +            <li>
- [ ] In my opinion, you can make your form more leaner and easy to read by removing the use of `<ul>` and its `<li>` from here. You can use something like:
```
<form>
   <input name />
   <input email />
   <textarea message />
   <button type="submit" />
</form>
```

2022-04-27 21:23 UTC, koomekevo requested changes
Hi @dqarias, 

<img src="https://media4.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 21:23 UTC, koomekevo commented on README.md
> +# My Portafolio Project
@dqarias Kindly rectify this typo as it should be `Portfolio` instead of `Portafolio`

2022-04-27 23:24 UTC, Davidosky007 reviewed
Hello @dqarias 👋,

_This is an additional review as a result of the second opinion request._

- I can see the only requested change by the last reviewer was an OPTIONAL suggestion by the first CR as a result the project should have been approved 🙏 

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)

Keep rocking 🚀!

2022-04-28 01:30 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @dqarias   , 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well implemented Figma design.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-28 01:48 UTC, merged